
# The Docker image that will be used to build your app
image: node:16.15.0
# Functions that should be executed before the build script is run
before_script:
  - npm i axios daisyui framer-motion react-dom
    react-helmet-async react-icons react-multi-carousel react-redux react-responsive-carousel
    react-router react-router-dom redux redux-thunk web-vitals react-scripts
  - npm i -D tailwindcss postcss autoprefixer @tailwindcss/typography @tailwindcss/forms
pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - react-scripts build
    - mv build public         
  artifacts:
    paths:
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
