# The Docker image that will be used to build your app
image: node
# Functions that should be executed before the build script is run
before_script:
  - ls -a
pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  variables:
    GIT_STRATEGY: git clone https://gitlab.com/wicahma/uts-rpl.git
  script:
    # Rename the CRA `build` folder to `public`
    - npm install
    - npm run-script build
    - mv build public
  artifacts:
    paths:
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
