# The Docker image that will be used to build your app
image: node:16.15.0
# Functions that should be executed before the build script is run
before_script:
  - npm i axios
  - npm i axios daisyui framer-motion react-dom
    react-helmet-async
  - npm i react-icons react-multi-carousel react-redux react-responsive-carousel
    react-router
  - npm i react-router-dom redux redux-thunk web-vitals react-scripts react@reduxjs/toolkit
pages:
  script:
    - npm start
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
